# Generated by Django 4.0.2 on 2022-06-02 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTeams',
            fields=[
                ('team_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Team ID')),
                ('team_name', models.CharField(max_length=25)),
                ('team_points', models.PositiveIntegerField(blank=True, default=0)),
                ('team_position', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Команди (учасників)',
            },
        ),
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('user_position', models.PositiveIntegerField(blank=True, default=0)),
                ('user_points', models.PositiveIntegerField(default=0)),
                ('user_potential_points', models.PositiveIntegerField(default=0)),
                ('user_average_point_per_match', models.FloatField(default=0.0)),
                ('user_all_predicted_matches', models.PositiveIntegerField(default=0)),
                ('user_predicted_match_score', models.PositiveIntegerField(default=0)),
                ('user_predicted_match_result', models.PositiveIntegerField(default=0)),
                ('user_predicted_express', models.PositiveIntegerField(default=0)),
                ('user_not_predicted_express', models.PositiveIntegerField(default=0)),
                ('user_achive_guru_turu', models.PositiveIntegerField(default=0)),
                ('user_team_name', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Підсумкова таблиця',
            },
        ),
        migrations.CreateModel(
            name='ListOfMatches',
            fields=[
                ('match_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Match ID')),
                ('round_numder', models.PositiveIntegerField(default=1)),
                ('match_in_round', models.PositiveIntegerField(default=1)),
                ('home_team', models.CharField(default='', max_length=20)),
                ('visitor_team', models.CharField(default='', max_length=20)),
                ('teams_together', models.CharField(default='', max_length=41)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('forecast_availability', models.CharField(default='no', max_length=3)),
                ('home_team_result', models.PositiveIntegerField(blank=True, null=True)),
                ('visitor_team_result', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Список мітчів',
            },
        ),
        migrations.CreateModel(
            name='ListOfUsersMatchForecast',
            fields=[
                ('forecast_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Forecast ID')),
                ('match_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('teams_together', models.CharField(default='', max_length=41)),
                ('home_team_forecast', models.PositiveIntegerField()),
                ('visitor_team_forecast', models.PositiveIntegerField()),
                ('round_numder', models.PositiveIntegerField(default=1)),
                ('forecast_time', models.DateTimeField(auto_now_add=True)),
                ('user_points', models.PositiveIntegerField(blank=True, null=True)),
                ('forecast_type', models.CharField(max_length=7)),
                ('match_in_round', models.PositiveIntegerField(default=1)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Прогнози всіх користувачів',
            },
        ),
    ]
