# Generated by Django 4.0.2 on 2022-06-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Зареєстровані Користувачі', 'verbose_name_plural': 'Зареєстровані Користувачі'},
        ),
    ]
