# Generated by Django 4.0.2 on 2022-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_remove_allteams_id_alter_allteams_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='allteams',
            name='team_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Team ID'),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='user_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
