# Generated by Django 4.0.2 on 2022-06-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listofmatches',
            old_name='round_numder',
            new_name='round_number',
        ),
        migrations.RenameField(
            model_name='listofusersmatchforecast',
            old_name='round_numder',
            new_name='round_number',
        ),
    ]
