# Generated by Django 4.0.2 on 2022-06-03 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_side', '0002_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofusersmatchforecast',
            name='users',
        ),
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_forecasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
