# Generated by Django 4.0.2 on 2022-06-03 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_side', '0003_remove_listofusersmatchforecast_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_fintable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_forecasts', to=settings.AUTH_USER_MODEL),
        ),
    ]
