# Generated by Django 4.0.2 on 2022-06-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_alter_finaltable_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='allteams',
            options={'verbose_name': 'Команди (учасників)', 'verbose_name_plural': 'Команди (учасників)'},
        ),
        migrations.AlterModelOptions(
            name='finaltable',
            options={'verbose_name': 'Підсумкова таблиця', 'verbose_name_plural': 'Підсумкова таблиця'},
        ),
        migrations.AlterModelOptions(
            name='listofmatches',
            options={'verbose_name': 'Список матчів', 'verbose_name_plural': 'Список матчів'},
        ),
        migrations.AlterModelOptions(
            name='listofusersmatchforecast',
            options={'verbose_name': 'Прогнози всіх учасників', 'verbose_name_plural': 'Прогнози всіх учасників'},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
