# Generated by Django 4.0.2 on 2022-05-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_remove_listofmatches_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteams',
            name='team_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Team ID'),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='user_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='listofmatches',
            name='match_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='forecast_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Forecast ID'),
        ),
    ]
