# Generated by Django 4.0.2 on 2022-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0008_alter_finaltable_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allteams',
            name='team_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='finaltable',
            name='user_team_name',
            field=models.CharField(blank=True, choices=[('team_1', 'team_1'), ('', '')], max_length=25),
        ),
    ]
