# Generated by Django 4.0.2 on 2022-05-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0009_alter_listofmatches_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmatches',
            name='match_time',
            field=models.TimeField(),
        ),
    ]
