# Generated by Django 4.0.2 on 2022-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0009_alter_allteams_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_team_name',
            field=models.CharField(blank=True, choices=[], max_length=25),
        ),
    ]
