# Generated by Django 4.0.2 on 2022-06-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0019_alter_finaltable_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_team_name',
            field=models.CharField(blank=True, choices=[], max_length=25),
        ),
    ]
