# Generated by Django 4.0.2 on 2022-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0020_alter_finaltable_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_team_name',
            field=models.CharField(blank=True, choices=[('team_1', 'team_1'), ('hghghgh', 'hghghgh'), ('test name 1', 'test name 1')], max_length=25),
        ),
    ]
