# Generated by Django 4.0.2 on 2022-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0026_alter_finaltable_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_team_name',
            field=models.CharField(blank=True, choices=[("<QuerySet [('team_1',)]>", 'Teams In Db'), ("[('team_1',)]", 'All Teams In Db'), ("[('team_1', 'team_1')]", 'User Team Choices'), ('team_1', 'Team'), ("('team_1', 'team_1')", 'Team Choices')], default='', max_length=25),
        ),
    ]
