# Generated by Django 4.0.2 on 2022-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0028_alter_finaltable_user_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
