# Generated by Django 4.0.2 on 2022-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0029_alter_finaltable_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltable',
            name='user_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
