# Generated by Django 4.0.2 on 2022-06-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0030_alter_finaltable_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.listofmatches'),
        ),
    ]
