# Generated by Django 4.0.2 on 2022-06-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DummyModel',
            new_name='CustomModel',
        ),
        migrations.AlterModelOptions(
            name='custommodel',
            options={'verbose_name_plural': 'Кастомні Admin операції'},
        ),
    ]
