# Generated by Django 4.0.2 on 2022-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0003_remove_allusers_id_alter_allteams_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofmatches',
            name='id',
        ),
        migrations.RemoveField(
            model_name='listofusersmatchforecast',
            name='id',
        ),
        migrations.AlterField(
            model_name='listofmatches',
            name='match_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Match ID'),
        ),
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='forecast_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Forecast ID'),
        ),
    ]
