# Generated by Django 4.0.2 on 2022-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_rename_user_achive_guru_tutu_finaltable_user_achive_guru_turu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmatches',
            name='match_date',
            field=models.DateField(),
        ),
    ]
