# Generated by Django 4.0.2 on 2022-05-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0008_alter_listofmatches_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmatches',
            name='match_time',
            field=models.DateTimeField(),
        ),
    ]
