# Generated by Django 4.0.2 on 2022-05-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0014_listofmatches_teams_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='forecast_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
