# Generated by Django 4.0.2 on 2022-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0015_alter_listofusersmatchforecast_forecast_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofusersmatchforecast',
            name='user_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
