# Generated by Django 4.0.2 on 2022-05-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0016_alter_listofusersmatchforecast_user_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllUsers',
        ),
    ]
