# Generated by Django 4.0.2 on 2022-05-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0017_delete_allusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allteams',
            options={'verbose_name_plural': 'Команди (учасників)'},
        ),
        migrations.AlterModelOptions(
            name='finaltable',
            options={'verbose_name_plural': 'Підсумкова таблиця'},
        ),
        migrations.AlterModelOptions(
            name='listofmatches',
            options={'verbose_name_plural': 'Список мітчів'},
        ),
        migrations.AlterModelOptions(
            name='listofusersmatchforecast',
            options={'verbose_name_plural': 'Прогнози всіх користувачів'},
        ),
    ]
