# Generated by Django 4.0.2 on 2022-05-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0018_alter_allteams_options_alter_finaltable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofmatches',
            name='forecast_availability',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
