# Generated by Django 4.0.2 on 2022-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTeams',
            fields=[
                ('team_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('team_points', models.PositiveIntegerField(default=0)),
                ('team_position', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('pass_hash', models.CharField(max_length=94)),
            ],
        ),
        migrations.CreateModel(
            name='FinalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=25)),
                ('user_position', models.PositiveIntegerField(default=0)),
                ('user_points', models.PositiveIntegerField(default=0)),
                ('user_potential_points', models.PositiveIntegerField(default=0)),
                ('user_average_point_per_match', models.FloatField(default=0.0)),
                ('user_all_predicted_matches', models.PositiveIntegerField(default=0)),
                ('user_predicted_match_score', models.PositiveIntegerField(default=0)),
                ('user_predicted_match_result', models.PositiveIntegerField(default=0)),
                ('user_predicted_express', models.PositiveIntegerField(default=0)),
                ('user_not_predicted_express', models.PositiveIntegerField(default=0)),
                ('user_achive_guru_tutu', models.PositiveIntegerField(default=0)),
                ('user_team_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.PositiveIntegerField()),
                ('round_numder', models.PositiveIntegerField(default=1)),
                ('match_in_round', models.PositiveIntegerField(default=1)),
                ('home_team', models.CharField(default='', max_length=20)),
                ('visitor_team', models.CharField(default='', max_length=20)),
                ('teams_together', models.CharField(default='', max_length=41)),
                ('match_date', models.CharField(max_length=10)),
                ('match_time', models.CharField(max_length=5)),
                ('forecast_availability', models.CharField(max_length=3)),
                ('home_team_result', models.PositiveIntegerField()),
                ('visitor_team_result', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListOfUsersMatchForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_id', models.PositiveIntegerField()),
                ('match_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('teams_together', models.CharField(default='', max_length=41)),
                ('home_team_forecast', models.PositiveIntegerField()),
                ('visitor_team_forecast', models.PositiveIntegerField()),
                ('round_numder', models.PositiveIntegerField(default=1)),
                ('forecast_time', models.CharField(max_length=9)),
                ('user_points', models.PositiveIntegerField()),
                ('forecast_type', models.CharField(max_length=7)),
                ('match_in_round', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
