# Generated by Django 4.0.2 on 2022-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allteams',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='allusers',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='listofmatches',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='listofusersmatchforecast',
            name='forecast_id',
        ),
        migrations.AlterField(
            model_name='allteams',
            name='team_points',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='allteams',
            name='team_position',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
