# Generated by Django 4.0.2 on 2022-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_remove_allteams_team_id_remove_allusers_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='id',
        ),
        migrations.AddField(
            model_name='allusers',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
