# Generated by Django 4.0.2 on 2022-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.IntegerField(default='')),
                ('id_item', models.PositiveIntegerField(default=0)),
                ('kids', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default='')),
                ('time', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
