# Generated by Django 4.0.2 on 2022-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_produntsincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputers',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phones',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='television',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
