# Generated by Django 4.0.2 on 2022-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalComputers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.CharField(default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.CharField(default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TeleVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.PositiveIntegerField(default=0)),
                ('available', models.CharField(default='No', max_length=3)),
            ],
        ),
    ]
