# Generated by Django 4.0.2 on 2022-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_askstories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduntsInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('prod_id', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price_one_product', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
