# Generated by Django 4.0.1 on 2022-01-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Askstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.IntegerField(default='')),
                ('id_item', models.PositiveIntegerField(default=0)),
                ('kids', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default='')),
                ('time', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Jobstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('id_item', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default='')),
                ('time', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=60)),
                ('url', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Newstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.IntegerField(default='')),
                ('id_item', models.PositiveIntegerField(default=0)),
                ('kids', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default='')),
                ('time', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=60)),
                ('url', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Showstories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(default='', max_length=100)),
                ('descendants', models.IntegerField(default='')),
                ('id_item', models.PositiveIntegerField(default=0)),
                ('kids', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default='')),
                ('time', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=60)),
                ('url', models.TextField(blank=True, default='')),
            ],
        ),
    ]
